---
security_autoupdate_mail_to: "root"
security_autoupdate_mail_on_error: false

certbot_certs:
  - domains: [ "parzival.pagina-dh.de" ]

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "parzival.pagina-dh.de"
    filename: "parzival.pagina-dh.de.conf"
    root: "/srv/parzival/htdocs"
    extra_parameters: |
      charset UTF-8;

      auth_basic "Parzival-Projekt - Rappoltsteiner Parzifal";
      auth_basic_user_file htpasswd;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /iiif {
        include fastcgi_params;
        fastcgi_pass iipsrv;
      }

  - listen: "443 ssl"
    root: "/srv/parzival/htdocs"
    server_name: "parzival.pagina-dh.de"
    filename: "parzival.pagina-dh.de-ssl.conf"
    extra_parameters: |
      ssl_certificate /etc/letsencrypt/live/parzival.pagina-dh.de/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/parzival.pagina-dh.de/privkey.pem;

      ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
      ssl_session_cache shared:ssl_session_cache:10m;
      ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
      ssl_prefer_server_ciphers on;

      charset UTF-8;

      auth_basic "Parzival-Projekt - Rappoltsteiner Parzifal";
      auth_basic_user_file htpasswd;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /iiif {
        include fastcgi_params;
        fastcgi_pass iipsrv;
      }

web_project_version: "development"
