#!/usr/bin/env node
// -*- mode: JS2 -*-

import "babel-polyfill";

import path from "path";
import { spawnSync } from "child_process";

import xfs from "fs-extra";

import transcript from "../build/transcript";

const base = path.resolve(__dirname, "..");
const htdocs = path.resolve(base, "htdocs");
const transcripts = path.resolve(base, "transcripts", "conversion");

const stdio = "inherit";

function run(cwd, ...args) {
    const { status } = spawnSync(...args, { cwd, stdio });
    if (status == 0) {
        return;
    }
    throw new Error(args);
}
run(transcripts, "docker", [
    "run", "-it", "--rm",
    "-v", `${transcripts}:/data`,
    "--env", "TUSTEP_CMD=xmlexport",
    "--env", "TUSTEP_INI=tustep.ini",
    "--env", "TUSTEP_MEM=00300000",
    "tustep"
]);

(async () => {
    await xfs.outputJson(
        path.resolve(htdocs, "transcript.json"),
        await transcript(transcripts)
    );
})();

run(base, "webpack", ["-p"]);
