#!/usr/bin/env node
// -*- mode: JS2 -*-

import "babel-polyfill";

import path from "path";
import { spawnSync } from "child_process";

import xfs from "fs-extra";

import transcript from "../build/transcript";

const base = path.resolve(__dirname, "..");
const htdocs = path.resolve(base, "htdocs");
const transcripts = path.resolve(base, "transcripts", "conversion");

const stdio = "inherit";
const env = {
    ...process.env,
    "TUSTEP_CMD": "xmlexport",
    "TUSTEP_INI": "tustep.ini",
    "TUSTEP_MEM": "00300000"
};

function run(cwd, ...args) {
    const { status } = spawnSync(...args, { cwd, stdio, env });
    if (status == 0) {
        return;
    }
    throw new Error(args);
}
run(transcripts, "tustep");

(async () => {
    await xfs.outputJson(
        path.resolve(htdocs, "transcript.json"),
        await transcript(transcripts)
    );
})();

run(base, "webpack", ["-p"]);
