# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.44"

  config.vm.synced_folder "../src/tustep", "/srv/parzival/host-tustep", create: true

  config.vm.provider "virtualbox" do |v|
    v.customize [ "modifyvm", :id, "--name", "parzival-dev", "--memory", "4096", "--uartmode1", "disconnected" ]
  end

  config.vm.provision "shell", inline: "test -e /usr/bin/python || apt-get -y update && apt-get -y install python-minimal"

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file}"
    ansible.galaxy_role_file = "roles.yml"
    ansible.playbook = "main.yml"
    ansible.become = true
  end
end
